---
output:
  pdf_document: default
  html_document: default
---

# Glosario

| English term                          | Traducción                              | Ejemplos                                                               | MX                                                              | ES                                                                      |
|---------------------------------------|-----------------------------------------|------------------------------------------------------------------------|-----------------------------------------------------------------|-------------------------------------------------------------------------|
| **A**                                 |                                         |                                                                        |                                                                 |                                                                         |
| access (verb)                         | acceder                                 | you access the column with `$`                                         |                                                                 | acceder a                                                               |
| accuracy                              | exactitud                               |                                                                        |                                                                 |                                                                         |
| arrange                               | organizar                               |                                                                        | ordenar                                                         |                                                                         |
| add-ons                               | complementos                            | add-ons                                                                | complementos                                                    | complementos o plugins                                                  |
| **B**                                 |                                         |                                                                        |                                                                 |                                                                         |
| backup                                | respaldar                               | backup your work                                                       | respaldar                                                       | respaldo o copia de seguridad                                           |
| bar plots                             | diagrama de barras                      |                                                                        |                                                                 |                                                                         |
| bin                                   | compartimiento                          |                                                                        |                                                                 |                                                                         |
| bindwidth                             | tamaño de compartimiento                |                                                                        |                                                                 |                                                                         |
| boxplot                               | diagrama de caja                        | display the data in a boxplot                                          | diagrama de caja y bigote                                       |                                                                         |
| **C**                                 |                                         |                                                                        |                                                                 |                                                                         |
| call                                  | llamada/llamar                          |                                                                        |                                                                 |                                                                         |
| character strings                     | cadenas de caracteres                   | vector of character strings                                            | secuencia de caracteres                                         | cadenas de caracteres                                                   |
| cheat sheet                           | hoja de referencia                      |                                                                        |                                                                 |                                                                         |
| click (verb)                          | clic, hacer clic                        |                                                                        | clic                                                            |                                                                         |
| clusters                              | grupos                                  |                                                                        |                                                                 |                                                                         |
| code                                  | código                                  | an R code                                                              |                                                                 |                                                                         |
| coerce (verb)                         | forzar una conversión                   | R coerced the data into characters                                     | forzar                                                          | convertir                                                               |
| coercion                              | conversión forzada                      |                                                                        |                                                                 |                                                                         |
| commands                              | comandos                                | type in the command                                                    | comando (singular) o comandos (plural)                          | comandos                                                                |
| command                               | tecla *command*                         | hit the command key                                                    | command o cmd                                                   | tecla de comando                                                        |
| **D**                                 |                                         |                                                                        |                                                                 |                                                                         |
| dashboard                             | tablero                                 | un *dashboard*                                                         |                                                                 |                                                                         |
| dataframe                             | marco de datos                          | tabla de datos                                                         | conjunto de datos                                               | datos                                                                   |
| data management                       | manejo de datos                         |                                                                        | manejo de datos                                                 | gestión de datos                                                        |
| data set                              | set de datos                            |                                                                        |                                                                 |                                                                         |
| data streaming processing             | procesamiento de flujos de datos        |                                                                        | procesamiento continuo de datos                                 | procesamiento de flujos de datos                                        |
| data types                            | tipos de datos                          | data types can be numeric, logical, ...                                | tipos de datos                                                  | tipos de datos                                                          |
| data wrangling                        | wrangling de datos                      |                                                                        | procesamiento de datos                                          | procesamiento de datos                                                  |
| dataset                               | set de datos                            |                                                                        |                                                                 |                                                                         |
| debug                                 | depurar                                 | makes it more difficult to debug the code                              | depurar                                                         | depurar                                                                 |
| default values                        | valores predeterminado                  |                                                                        | valores predeterminado, valor inicial                           | valores por defecto, valores predeterminados                            |
| density curve                         | la curva de densidad                    |                                                                        |                                                                 |                                                                         |
| density plot                          | gráfico de densidad                     |                                                                        |                                                                 |                                                                         |
| **E**                                 |                                         |                                                                        |                                                                 |                                                                         |
| editing panel                         | panel de edición                        | the editing panel                                                      |                                                                 | panel de edición                                                        |
| element-wise                          | elemento por elemento                   |                                                                        |                                                                 |                                                                         |
| execute (verb)                        | ejecutar                                | to execute the code                                                    | ejecutar                                                        | ejecutar                                                                |
| **F**                                 |                                         |                                                                        |                                                                 |                                                                         |
| F score                               | medida F                                |                                                                        |                                                                 |                                                                         |
| false positive rate                   | tasa de falsos positivos                |                                                                        |                                                                 |                                                                         |
| facet                                 | faceta                                  | facet_grid()                                                           |                                                                 |                                                                         |
| fill                                  | llenar                                  | fill color                                                             | color de llenado                                                | color de fondo                                                          |
| file (verb)                           | archivar                                | to file                                                                |                                                                 |                                                                         |
| file (noun)                           | archivo                                 | save the script in a file                                              | Archivo                                                         | archivo o fichero                                                       |
| folds                                 | pliegues                                |                                                                        |                                                                 |                                                                         |
| for-loop                              | bucle-for                               |                                                                        |                                                                 | bucle-for                                                               |
| functions                             | funciones                               | We will use the functions `mean` and `sd`                              | funciones                                                       | funciones o rutina                                                      |
| function call                         | llamada a función                       | there is no difference between this function call and the previous one | llamada a función                                               | llamadas a funciones, invocar función                                   |
| **H**                                 |                                         |                                                                        |                                                                 |                                                                         |
| help                                  | ayuda                                   |                                                                        |                                                                 |                                                                         |
| History                               | historial                               |                                                                        |                                                                 |                                                                         |
| **I**                                 |                                         |                                                                        |                                                                 |                                                                         |
| image plot                            | mapa de matriz                          |                                                                        |                                                                 |                                                                         |
| index (verb)                          | indexar                                 | integers are used to index vectors                                     | indexar, indizar                                                | indexar                                                                 |
| indexing                              | indexación                              | R provides a convenient way of indexing vectors                        |                                                                 | indexación                                                              |
| input (noun)                          |                                         | entrada                                                                | `mean` takes a vector as input                                  | input (no se traduce; anglicismo aceptado), entrada                     |
| input (adjetive)                      | input, de entrada                       | `x` is the input vector                                                | input, de entrada                                               | de entrada                                                              |
| input function (for machine learning) | atributo de entrada                     |                                                                        |                                                                 |                                                                         |
| input layer (for machine learning)    | capa de entrada                         |                                                                        |                                                                 |                                                                         |
| intercept                             | intercepto                              |                                                                        | intercepto, intersección                                        |                                                                         |
| **J**                                 |                                         |                                                                        |                                                                 |                                                                         |
| **K**                                 |                                         |                                                                        |                                                                 |                                                                         |
| key bindings                          | atajo de teclado                        | combinaciones de teclas                                                |                                                                 |                                                                         |
| keyboard shortcut                     | Use the keyboard shortcut command-S     | atajo del teclado                                                      | atajo de teclado                                                |                                                                         |
| **L**                                 |                                         |                                                                        |                                                                 |                                                                         |
| log odds ratio                        | logaritmo de riesgo relativo            |                                                                        |                                                                 |                                                                         |
| log transformation                    | transformación logarítmica              |                                                                        |                                                                 |                                                                         |
| logical operators                     | operadores lógicos                      |                                                                        |                                                                 |                                                                         |
| logicals                              | lógicos o booleanos                     | to get a vector of logicals                                            | operadores lógicos o booleanos                                  | lógicos o booleanos                                                     |
| loop                                  |                                         | bucle                                                                  |                                                                 |                                                                         |
| loss function                         | función de pérdida                      |                                                                        |                                                                 |                                                                         |
| **M**                                 |                                         |                                                                        |                                                                 |                                                                         |
| machine learning                      | *machine learning*                      |                                                                        | machine learning o la traducción literal aprendizaje de máquina |                                                                         |
| map (noun)                            | mapeo                                   |                                                                        |                                                                 |                                                                         |
| map (verb)                            | definir una correspondencia o mapear    |                                                                        |                                                                 |                                                                         |
| mapping                               | correspondencia                         |                                                                        | mapear                                                          |                                                                         |
| (aesthetic) mappings                  | mapeos estéticos                        |                                                                        |                                                                 |                                                                         |
| match (verb)                          | aparear                                 |                                                                        | coincidencia                                                    |                                                                         |
| match (noun)                          | apareado                                |                                                                        | coincidencia                                                    |                                                                         |
| matrix of logicals                    | matriz de valores lógicos               |                                                                        |                                                                 |                                                                         |
| maximum likelihood estimation         | estimación de máxima verosimilitud      |                                                                        |                                                                 |                                                                         |
| mean                                  | media                                   |                                                                        | promedio                                                        | media                                                                   |
| mean square error                     | error cuadrático medio                  |                                                                        |                                                                 |                                                                         |
| median                                | mediana                                 |                                                                        |                                                                 |                                                                         |
| missing data                          | datos faltantes                         |                                                                        | datos perdidos                                                  |                                                                         |
| missing value                         | valor faltante                          |                                                                        | valor faltante                                                  |                                                                         |
| modelling                             | modelando                               |                                                                        | modelado                                                        |                                                                         |
| **N**                                 |                                         |                                                                        |                                                                 |                                                                         |
| named list                            | lista con nombres                       |                                                                        | lista nombrada                                                  |                                                                         |
| notebook                              |                                         | un *notebook*                                                          |                                                                 |                                                                         |
| **O**                                 |                                         |                                                                        |                                                                 |                                                                         |
| operator                              | operador                                | the `!=` operator                                                      | operador                                                        | operador                                                                |
| order                                 | ordenar                                 |                                                                        |                                                                 |                                                                         |
| outliers                              | valores atípicos                        |                                                                        |                                                                 |                                                                         |
| output                                | *output*, resultado, salida             | the output of the function is a vector                                 | un *output* (no se traduce),resultado, salida                   | salida                                                                  |
| output layer                          | capa de salida                          |                                                                        |                                                                 |                                                                         |
| overall accuracy                      | exactitud general                       |                                                                        |                                                                 |                                                                         |
| **P**                                 |                                         |                                                                        |                                                                 |                                                                         |
| packages                              | paquetes                                | R packages                                                             | librerías                                                       |                                                                         |
| panels                                | paneles                                 |                                                                        |                                                                 |                                                                         |
| parse                                 | leer y procesar                         |                                                                        |                                                                 |                                                                         |
| path                                  | ruta                                    | Relative and full paths, the path of a file list                       | rutas                                                           | ruta                                                                    |
| pipe                                  | *pipe*                                  | `%>%`                                                                  | *pipe*                                                          | tubería                                                                 |
| pipe (verb)                           | canalizar                               | We can continue to pipe values along                                   |                                                                 |                                                                         |
| pipeline                              | canalización                            |                                                                        |                                                                 |                                                                         |
| placeholder                           | marcador de posición                    |                                                                        | marcador de posición                                            |                                                                         |
| plot (noun)                           | gráfico                                 | make a plot of the data                                                | gráfico, gráfica                                                | gráfico                                                                 |
| plot (verb)                           | graficar                                | plot the data                                                          | graficar                                                        | graficar, representar                                                   |
| **Q**                                 |                                         |                                                                        |                                                                 |                                                                         |
| Q-Q plot                              | gráfico Q-Q                             |                                                                        |                                                                 |                                                                         |
| query                                 | consulta                                |                                                                        | consulta                                                        |                                                                         |
| quote (verb)                          | entrecomillar                           | we need to quote strings                                               | entrecomillar                                                   |                                                                         |
| **R**                                 |                                         |                                                                        |                                                                 |                                                                         |
| recall                                | recall                                  |                                                                        |                                                                 |                                                                         |
| residual sum of squares (RSS)         | suma de errores cuadrados o RSS         |                                                                        |                                                                 |                                                                         |
| R software environment                | ambiente de *software* R                |                                                                        | ambiente de trabajo en R                                        | entorno de R                                                            |
| R environment                         | ambiente de R                           |                                                                        | ambiente de R/ambiente de trabajo                               | entorno de R                                                            |
| raw data                              | datos sin procesar                      |                                                                        | datos sin procesar, datos crudos                                |                                                                         |
| read-in                               | leer, importar                          |                                                                        | leer (a veces "importar")                                       | leer                                                                    |
| refresh                               | actualizar                              |                                                                        | actualizar                                                      |                                                                         |
| regular expression                    | expresión regular                       |                                                                        | expresión regular                                               |                                                                         |
| relational operators                  | operadores relacionales                 | `>` and `<` are relational operators                                   | símbolos de relación                                            | operadores relacionales                                                 |
| return key                            | tecla *return*                          |                                                                        |                                                                 | tecla de retorno, <ENTER>                                               |
| run                                   | correr, ejecutar                        | to run the code                                                        | correr, ejecutar                                                | ejecutar                                                                |
| **S**                                 |                                         |                                                                        |                                                                 |                                                                         |
| sample                                | muestras                                |                                                                        |                                                                 |                                                                         |
| scaling                               | ajuste                                  |                                                                        |                                                                 |                                                                         |
| scale                                 | escala                                  | scale_manual                                                           |                                                                 |                                                                         |
| scatterplot                           | diagrama de dispersión                  |                                                                        | diagrama de dispersión, diagrama de puntos                      | diagrama de dispersión                                                  |
| script                                | *script*                                | write an R script                                                      | script                                                          | script, archivo de procesamiento por lotes (en MSDOS, Unix/Linux, etc.) |
| sd                                    | desviación estándar                     | standard deviation                                                     |                                                                 |                                                                         |
| smooth                                | suave                                   | smooth densities                                                       | densidades suaves                                               |                                                                         |
| smoothing                             | suavización                             |                                                                        |                                                                 |                                                                         |
| sofware                               | *programa*                              |                                                                        | software                                                        | software                                                                |
| software engineer                     | ingeniero de programas                  |                                                                        | ingeniero de software                                           | ingeniero de software, ingeniero informático                            |
| sort                                  | ordenar alfabeticamente o numericamente | sort the rows of this data frame                                       |                                                                 |                                                                         |
| spline                                | *spline*                                |                                                                        | un *spline*                                                     |                                                                         |
| spreadsheets                          | hoja de cálculo                         |                                                                        | planilla de cálculo                                             | hoja de cálculo                                                         |
| subset                                | (extraer/crear) subconjunto             | (extraer/crear) subconjunto                                            | (crear un) subconjunto                                          |                                                                         |
| stacked                               | apilado                                 |                                                                        |                                                                 |                                                                         |
| string                                | cadenas                                 |                                                                        |                                                                 |                                                                         |
| statistic                             | estadístico                             |                                                                        |                                                                 |                                                                         |
| summary statistics                    | resumen estadístico                     |                                                                        |                                                                 |                                                                         |
| **T**                                 |                                         |                                                                        |                                                                 |                                                                         |
| t statistic                           | estadística t o prueba t                |                                                                        |                                                                 |                                                                         |
| tabs                                  | pestañas                                | RStudio has a Viewer tab                                               | pestañas                                                        | pestañas                                                                |
| tidy data                             | datos *tidy*                            |                                                                        |                                                                 | datos ordenados                                                         |
| tidy format                           | formato *tidy*                          | this data is in tidy format                                            |                                                                 |                                                                         |
| theme                                 | tema                                    |                                                                        |                                                                 |                                                                         |
| true positive rate                    | tasa de positivos verdaderos            |                                                                        |                                                                 |                                                                         |
| **U**                                 |                                         |                                                                        |                                                                 |                                                                         |
| **V**                                 |                                         |                                                                        |                                                                 |                                                                         |
| View (verb)                           | ver                                     |                                                                        |                                                                 |                                                                         |
| Viewer                                | Visor                                   |                                                                        |                                                                 |                                                                         |
| **W**                                 |                                         |                                                                        |                                                                 |                                                                         |
| web-based                             | disponible en la web                    |                                                                        | en linea/disponible en la web,                                  | en la web                                                               |
| web scraping                          | extracción de la web                    |                                                                        | descarga/extracción de información en linea                     | extracción de la web, rastreo web                                       |
| weighted                              | ponderado                               |                                                                        |                                                                 |                                                                         |
| working directory                     | directorio de trabajo                   |                                                                        | directorio de trabajo                                           | carpeta donde estás trabajando                                          |
| workspace                             | espacio de trabajo                      | save it in the workspace                                               | espacio de trabajo                                              | espacio de trabajo                                                      |
| **X**                                 |                                         |                                                                        |                                                                 |                                                                         |
| **Y**                                 |                                         |                                                                        |                                                                 |                                                                         |
| **Z**                                 |                                         |                                                                        |                                                                 |                                                                         |
